name: cemac_data_observatory
version: "1.0.0"
config-version: 2

profile: cemac

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cemac_data_observatory:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table

seeds:
  cemac_data_observatory:
    +schema: staging
